version: "3"
services:
 caddy:
   image: stefanprodan/caddy
   container_name: caddy
   ports:
    - "443:443"
    - "80:80"
   volumes:
    - ./caddy/:/etc/caddy/
#     - ./caddy-certy/:/root/.caddy/
   networks:
   - front-certi

 backend-node:
   build: ./backend/nodejs
   container_name: 'backend-node'
   ports:
    - "5000:5000"
   volumes:
    - ${BACK}:/app
   networks:
   - front-certi

 frontend-node:
   build: ./frontend
   container_name: 'frontend-node'
   ports:
     - 4200:4200
     - 5001:5001
     - 3000:3000
   volumes:
    - ${FRONT}:/frontend

   networks:
   - front-certi

networks:
  front-certi:
    driver: bridge

